package ${basePackage}.service.${sign};
import ${basePackage}.model.${sign}.${modelNameUpperCamel};
import ${basePackage}.service.Service;

/**
 *
 * Auto Generated by ${author} on ${date}.
 */
public interface ${modelNameUpperCamel}Service extends Service<${modelNameUpperCamel}> {

}
